### PR TITLE
fix: resolve 'indexOf' of undefined in some cases

### LINKED ISSUE #30: Cannot read property 'indexOf' of undefined
### Description of the issue

In some cases, I've got the following error: Cannot read property 'indexOf' of undefined

### Steps to reproduce

See the attached file
[error.js.txt](https://github.com/Ma27/eslint-plugin-varspacing/files/1599853/error.js.txt)

### Expected behavior

I shouldn't have any errors

### Additional information
There is the complete error:

```
Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at parseStatements ([...]/node_modules/eslint-plugin-varspacing/lib/util/findNextPunctuators.js:62:29)
    at module.exports ([...]/node_modules/eslint-plugin-varspacing/lib/util/findNextPunctuators.js:19:39)
    at expressionCheck ([...]/node_modules/eslint-plugin-varspacing/lib/rules/var-spacing.rule.js:41:7)
    at listeners.(anonymous function).forEach.listener ([...]/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit ([...]/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector ([...]/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors ([...]/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode ([...]/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode ([...]/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
```

### PR DESCRIPTION
**Pull request by Darkein**
### Overview

in some cases, findParentTokens return null instead of an empty array. This PR prevent this.

### Related/Resolved tickets

all tickets that are related to the PR should be placed here...
Fixes #30

### Breaking changes

no breaking changes

### CODE REVIEW

**Comment by Ma27** [comment]
Hi @Darkein,

at first thanks a lot for your contribution! However could you please add a testcase or at least some code which breaks with this ESLint plugin?

**Comment by Darkein** [comment]
Hello @Ma27 , thanks for your plugin :)

I added the file whose break the plugin in the issue. Do you want me to add it also in the PR?

**Comment by Ma27** [comment]
We have a file with several test cases (https://github.com/Ma27/eslint-plugin-varspacing/blob/master/test/lib/rules/var-spacing.rule.js) that can be tested running `npm test`.
It would be great if you could add the code which broke the plugin in there.

Optionally you could add a gist with the affected file and I write the test case for you :-)

**Comment by Darkein** [comment]
The file in the issue break the plugin, but i don't know witch part of it :/
I will create a gist with this file, maybe you will find before me what is the problem :)

I'm sorry, that's my first contribution on Github, i don't master the PR process

You can access to the gist [here](https://gist.github.com/Darkein/bf80d094c65e0498b0116ff5390fd6a9) (please don't look the ugly code)

**Comment by Ma27** [comment]
> The file in the issue break the plugin, but i don't know witch part of it :/
I will create a gist with this file, maybe you will find before me what is the problem :)

Understood. However I'm not sure if I can make this today, so it might take some time.

> I'm sorry, that's my first contribution on Github, i don't master the PR process

That's fine, I think it's wrong to judge people because of that :-)

**Comment by Darkein** [comment]
I've found the faulty code: `if (i % $scope.modulo != 0) xLabels[i] = '';`, I don't have any problem if i write it like this: `if (i % $scope.modulo != 0){ xLabels[i] = '';}`

I've disabled the plugin in my projet, added the curly:all rule to eslint, fix all the files, re-enabled the plugin and now i don't have any errors.

I will add it to var-spacing rules and try to improve my PR :)

**Comment by Ma27** [comment]
> I will add it to var-spacing rules and try to improve my PR :)

awesome! Just ping me if you have any further questions :-)

**Comment by Ma27** [comment]
@Darkein is there anything I can help with?

**Comment by Darkein** [comment]
I don't have the time to work on it this week. I will look the next week!

**Comment by Darkein** [comment]
Hi, I just tried to add some tests, but without changing any line of code I don't have any errors, even if I break one of your test...

Can you try this test with your config?
```
{
      code: [
        'if(true)',
        'var foo = {};',
        'var bar  = {};'
      ].join('\n'),
      errors: [{
        message: 'Invalid indent!'
      }],
      output: [
        'if(true)',
        '  var foo = {};',
        'var bar = {};'
      ].join('\n')
    }
```

**Comment by Ma27** [comment]
will have a look at it on the weekend :)

**Comment by noisygerman** [comment]
Just looked at this and ran @Darkein's test config against the PR's code. With that PR, I always get a failing test. 

I seems that the plugin ignores unbracketed branches. This code

```javascript
if(true)
var foo = {};
var bar = {};
```

seems to be ok as far as the current implementation of the rule is concerned.

The rule is failing for me for a similar the same reason:

```javascript
// didn't like this either
if( path != null ) value = get( path );
```

workaround:
```javascript
value = path == null
  ? value
  : value = get( path );
```
it seems the problem is in `findParentTokens`. I can *try* (between, kid's soccer, ballet, swimming and the like 😀) to take a look at this over the weekend as well.

I would assume that we would want the below for this rule:

```javascript
// Good
if(true) value = {};

// Good
if(true)
  value = {};

// Good (as far as the rule is concerned)
if(true)
  var value = {};

// Good (as far as the rule is concerned)
if(true)
  const value = {}; 
```

**Comment by Ma27** [comment]
at first thanks a lot @noisygerman for your investigation!

> I seems that the plugin ignores unbracketed branches. This code

That's right. I'll have to confirm it, but I'm quite sure that the AST generated by ESLint contains some kind of `IfExpression` node with all declarations inside, so the current implementation is unable to find anything in such cases.

> I would assume that we would want the below for this rule:

full ACK. There's just one additional case that should be taken care of:

``` js
if (cond)
  a = b;
n = m;
```

The main intention of this plugin was to make many variable declarations easier to read. However aligning declarations where one of them lives in an If-Expression can be confusing.

> it seems the problem is in findParentTokens. I can try (between, kid's soccer, ballet, swimming and the like 😀) to take a look at this over the weekend as well.

Just take the time you need, it's just open source. If you don't have sufficient time to, I can have a look at this next, however I have a lot of exams to prepare ATM, so I don't know how much I can do about this :-)

**Comment by Ma27** [comment]
@noisygerman @Darkein did you have any time for investigation? I somehow forgot about this issue, I may have some time to have a second look on this, but I'd love to hear if you got something before :)

**Comment by noisygerman** [comment]
@Ma27 I started on it and then got too busy with other things. But yeah, we are hitting this issue frequently, especially the conditional assignment.

One thing I came across:

I don't think that this plugin should modify:

```js
if (cond)
a = b;
c = d;
```

to 

```js
if (cond)
  a = b;
c = d;
```

and definitely not

```js
if (cond)
  a = b;
c   = d;
```

It should not to anything, since its job is to align assignment operators, not fix the indentation before the assignment. It's actually why I stopped when I realized I had to test differently...

so:

```js
// Good
if(true) value = {};

// Good, because value2 is not part of the same block
if(true)
const value = {};
const value2 = {};
```

Thoughts?

**Comment by Ma27** [comment]
yes, agreed.
I'll check if the PR works sufficiently and add your example as testcases. In case everything works fine I'd merge this, otherwise I'd report the issues I'm experiencing :)

**Comment by Ma27** [comment]
ok, tests work, the original issue is obviously solved, let's merge this for now (this package could use a new release :D)

**Pull request merged**
